### ISSUE TITLE
User can View jokes from their chosen category

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/crackin-jokes#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a category and view a random joke from chosen category.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click one of two buttons that will generate a joke for them. They can choose to see the punchline or go back to the home page at any time.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="372" alt="Screen Shot 2021-04-13 at 12 45 10 PM" src="https://user-images.githubusercontent.com/74742148/114611674-24981800-9c56-11eb-9a0e-1e2bf916004a.png">
<img width="370" alt="Screen Shot 2021-04-13 at 12 45 56 PM" src="https://user-images.githubusercontent.com/74742148/114611823-44c7d700-9c56-11eb-9513-d2a3188daf5c.png">
<img width="373" alt="Screen Shot 2021-04-13 at 12 46 43 PM" src="https://user-images.githubusercontent.com/74742148/114611866-50b39900-9c56-11eb-932b-a63cedfeeb83.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create data model
- [x] Add a div for the homepage
- [x] Make sure it looks good on mobile and desktop
- [x] Add view for general jokes
- [x] Make sure it looks good on mobile and desktop
- [x] Add View for programming jokes
- [x] Make sure it looks good on mobile and desktop
- [x] Listen for click events on buttons
    - [x] Ensure that clicking on a given button changes to the correct view
    - [x] When a category is clicked, get data from api  (joke of chosen category) and append to page
    - [x] When Tell Me button is clicked, get data from api (punchline of chosen category) and append to page, clear last joke from page
    - [x] When Another button is clicked, data from api appends a new joke of chosen category, clear last punchline
    - [x] Ensure home button brings user back to the home page
- **Clean Up**
- [x] Remove all CSS that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Fix any bugs
