### ISSUE TITLE
User can Save their favorite jokes

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/crackin-jokes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite jokes that they like

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the star at the top right hand side of the joke they like to favorite/save it

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="174" alt="Screen Shot 2021-04-13 at 12 53 06 PM" src="https://user-images.githubusercontent.com/74742148/114612656-41811b00-9c57-11eb-8bad-8a08e4b8db11.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Favorite star icon changes color when clicked and goes back to original color when clicked again
- [x] Clicking the star once puts the joke into the data model
- [x] Clicking the star again removes the joke from the data model
- [x] Store data into local storage
- [x] Ensure data is still there after refreshing the page
- **Clean Up**
  - [x] Remove all unnecessary CSS.
  - [x] Check functionality still works 
  - [x] Fix any and all bugs
