### ISSUE TITLE
User can View all their favorite jokes

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/crackin-jokes#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can View a list of their favorite jokes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the star at the bottom right corner (mobile) or click "Favorites" at the top right of the page (Desktop) to view a list of their favorite jokes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="181" alt="Screen Shot 2021-04-16 at 12 52 46 PM" src="https://user-images.githubusercontent.com/74742148/115077328-bac87a00-9eb2-11eb-8635-b7249086ecf2.png">
<img width="415" alt="Screen Shot 2021-04-16 at 6 33 27 PM" src="https://user-images.githubusercontent.com/74742148/115097992-4c031500-9ee2-11eb-9cea-6ae923d81fae.png">

<img width="452" alt="Screen Shot 2021-04-13 at 12 56 51 PM" src="https://user-images.githubusercontent.com/74742148/114613056-b94f4580-9c57-11eb-8aad-4f011dde0219.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make a data-view for the favorites page
- [x] Add needed styling through CSS
- [x] Make sure the view looks good on mobile and desktop
- [x] Ensure clicking on the star nav icon displays the correct view and hides all other views
- [x] Make a function that appends data to the page when a joke is added to the data model
- [x] Check that data is still there after refresh
- [x] Remove dummy data
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Fix any and all bugs
  - [x] Remove comments and console logs if any
