### ISSUE TITLE
User can Remove a joke from their favorites list

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/crackin-jokes#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove jokes from their favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can go to their favorites list and click the gold star to the right of their joke to unfavorite it and remove it from the list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="181" alt="Screen Shot 2021-04-16 at 12 52 46 PM" src="https://user-images.githubusercontent.com/74742148/115132284-c6e83080-9fb3-11eb-9612-b6c7b7dd7bd2.png">
<img width="415" alt="Screen Shot 2021-04-16 at 6 33 27 PM" src="https://user-images.githubusercontent.com/74742148/115132286-c94a8a80-9fb3-11eb-99ba-5e523e099f4f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Ensure when user clicks star icon once it removes the joke from the page
- [x] Ensure when user clicks star icon once it removes the joke from the data model
- **Clean Up**
  - [x] Make sure styling still looks good after removing joke
  - [x] Fix any errors and bugs
