### ISSUE TITLE
User can Search through their favorites using a keyword

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/crackin-jokes#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a joke in their favorites list using a keyword

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click in the search bar to type a word. Jokes containing that word will be shown to the user

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="181" alt="Screen Shot 2021-04-16 at 12 52 46 PM" src="https://user-images.githubusercontent.com/74742148/115314303-c40f4c00-a129-11eb-9373-4c987682111b.png">
<img width="415" alt="Screen Shot 2021-04-16 at 6 33 27 PM" src="https://user-images.githubusercontent.com/74742148/115314311-c671a600-a129-11eb-89d5-625a53e2225e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a function that checks the user input in the search bar. Log the input to the console to make sure it works
- [x] Create a function to check text content of each joke and show jokes that include the user's input
- **Clean Up**
  - [x] Remove unnecessary CSS
  - [x] Check all functionality still works
  - [x] Fix any bugs
  - [x] Remove any console logs and commented out code
